version: "3.3"
services:

  jenkins:
    build: .
    volumes:
      - jenkins:/var/jenkins_home
    ports:
      - "8000:8080"
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=password
    networks:
      - jenkins
  web:
    build: ./web
    ports:
      - "8080:80"
      - "1022:22"
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins:
